blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/', views.tag_list, name='tag_list'),
    path('signup/', views.signup, name='signup'),
    path('login/',views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('post/', views.post_new, name='post_new'),
    path('category/', views.category_list, name='category_list'),
    path('post/<slug:slug>/edit/', views.post_edit, name='post_edit'),
    path('category/<slug:slug>/', views.category_post, name='category_post'),
    path('post/<int:post_id>/comments/', views.post_detail, name='post_detail'),
    path('user/<int:user_id>/edit/', views.edit_profile, name='edit_profile'),
    path('user/<int:user_id>/', views.user_detail, name='user_detail'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('tag/<slug:slug>/', views.tag_post, name='tag_post'),
   
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("", views.IndexView.as_view(), name="index"),
]

blog/models.py
from asyncio import AbstractServer
from django.db import models
from django.utils import timezone
from autoslug import AutoSlugField
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils.html import mark_safe
from PIL import Image


class User(AbstractUser):
    
    email = models.EmailField(unique=True, null=True, db_index=True)
    dob = models.DateField(null=True, blank=True)
    mobile_number = models.IntegerField( null=True, blank=True)
    about  = models.CharField(max_length=15, null=True, blank=True)     
    city =models.CharField(max_length=15,)
    country = models.CharField(max_length=15,)
    avatar = models.ImageField(upload_to='profile_pics', null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Corrected line
        if self.avatar:
            img = Image.open(self.avatar.path)
            if img.height > 150 or img.width > 150:
                output_size = (150, 150)
                img.thumbnail(output_size)
                img.save(self.avatar.path)
    def get_email(self):
        return self.email
    
    def __str__(self):
        return self.username

class Category(models.Model):
    title = models.CharField(max_length=200,null=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = AutoSlugField(populate_from='title',unique=True)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title    


class Tag(models.Model):
    title = models.CharField(max_length=200,null=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = AutoSlugField(populate_from='title',unique=True)
    
    def __str__(self):
        return self.title
    

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200,null=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = AutoSlugField(populate_from='title',unique=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    thumbnail = models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    feature_image=models.ImageField(upload_to='feature_image/',null=True, blank=True)

    def thumbnail_tag(self):
        if self.thumbnail:
            return mark_safe(f'<img src="{self.thumbnail.url}" width="50" height="50" />')
        else:
            return 'No Thumbnail'

    thumbnail_tag.short_description = 'Thumbnail'


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
    def get_comments(self):
        return self.comments.all()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,)
    reply = models.ForeignKey('self',related_name=("replies"), on_delete = models.CASCADE , blank= True ,null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    name =models.CharField(max_length=200,null=True)


    def __str__(self):
        return "Comment by {self.author} on {self.post.title}"

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm ,UserChangeForm
from django.core.validators import RegexValidator
from .models import Post ,User,Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text','category','tags','thumbnail','feature_image')

class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = '__all__'


class SignUpForm(UserCreationForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    mobile_number = forms.IntegerField(
        validators=[
            RegexValidator(
                regex='^\d+$',
                message='Mobile number must contain only numeric digits.',
                code='invalid_mobile_number'
            )
        ],
        required=False
    )    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'city', 'country', 'dob','mobile_number','avatar']


class LoginForm(AuthenticationForm):
    print('U=I am here')
    def get_email(self):
        
        return self.cleaned_data.get('email')
    class Meta:
        model = User


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['email','mobile_number','dob','city','country', 'avatar']
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name' ,'text' ]


class EmailOrUsernameAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=254)

blog/views.py
from django.utils import timezone
from  django.shortcuts import render, get_object_or_404 ,redirect
from django.contrib.auth import login 
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm , authenticate
from django.contrib.auth import logout
from .forms import  * 
from .models import *

def post_list(request, category_slug=None):
    posts = Post.objects.all().order_by('published_date')
  
    return render(request, 'blog/post_list.html', {'posts': posts, })


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post, parent_comment=None)
    comment_form = CommentForm()
    reply_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.created_date = timezone.now()
            parent_comment_id = request.POST.get('parent_comment_id')

            if parent_comment_id:
                parent_comment = get_object_or_404(Comment, id=parent_comment_id)
                comment.parent_comment = parent_comment

            comment.save()
            return redirect('post_detail', slug=post.slug)

    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'reply_form': reply_form})



def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES,)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('post_list')
        
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

 

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'blog/category_list.html', {'categories': categories})

def category_post(request, slug):
    category = Post.objects.filter(category__slug = slug)
    print(category)
    return render(request, 'blog/post_list.html', {'posts': category})
 
def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'blog/tag_list.html', {'tags': tags})

def tag_post(request, slug):
    tag = Post.objects.filter(tags__slug = Tag.objects.filter(slug=slug).last().slug)
    
    return render(request,'blog/post_list.html', {'posts': tag})
  
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('post_list')
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        try:
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                return redirect('post_list')  
            else:
                user=form.get_email()
                login(request,user)
                return redirect('post_list')
        except:
            form = LoginForm()
            return render(request, 'blog/user_login.html', {'form': form})
           
    else:
        form = LoginForm()
        return render(request, 'blog/user_login.html', {'form': form})

def user_logout(request):
    logout(request)
    
    return redirect('post_list' )

def user_detail(request, user_id):
    print(user_id)
    print("---------")
    user = get_object_or_404(User, id=user_id,)
    
    
    return render(request, 'blog/user_detail.html', {'user': user})

def edit_profile(request, user_id):
    user = User.objects.get(id=user_id)

    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES, instance=request.user)
        if form.is_valid():
            form.save()

            messages.success(request, 'Your profile was successfully updated.')
            return redirect('user_detail', user_id=user.id)  
        else:
            messages.error(request, 'There was an error updating your profile. Please correct the errors below.')
    else:
        form = EditProfileForm(instance=request.user)

    return render(request, 'blog/edit_profile.html', {'user': user, 'form': form})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>H E R A P H E R I Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }
        .page-header {
            background-color: #343a40;
            padding: 20px;
            color: #ffffff;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        .navbar-brand {
            font-family: 'Lobster', sans-serif;
            font-size: 2rem;
            color: #ffffff;
            text-decoration: none;
        }
        .navbar-brand:hover {
            color: #f8f9fa;
        }
        .navbar a {
            color: #ffffff;
            text-decoration: none;
            transition: color 0.3s ease-in-out;
            margin-left: 15px;
            font-size: 1rem;
            font-weight: bold;
        }
        .navbar a:hover {
            color: #f8f9fa;
        }
        .btn-logout,
        .btn-create-post,
        .btn-login,
        .btn-signup,
        .btn-categories,
        .btn-tags,
        .btn-polls {
            transition: background-color 0.3s ease-in-out, border-color 0.3s ease-in-out, color 0.3s ease-in-out;
            font-size: 1rem;
            font-weight: bold;
            padding: 10px 15px;
            border-radius: 5px;
        }
        .btn-logout:hover,
        .btn-create-post:hover,
        .btn-login:hover,
        .btn-signup:hover,
        .btn-categories:hover,
        .btn-tags:hover,
        .btn-polls:hover {
            filter: brightness(90%);
        }
        .btn-create-post {
            background-color: #007bff;
            border-color: #007bff;
            color: #ffffff;

        }
        .logout-container {
            text-align: right;
            margin-top: 10px; 
        }


        .btn-logout {
            background-color: #dc3545;
            border-color: #dc3545;
            color: #ffffff;
            text-align: right;
        }
        .btn-login,
        .btn-signup,
        .btn-categories,
        .btn-tags,
        .btn-polls {
            background-color: transparent;
            border: none;
            color: #000000;
            font-weight: bold;
            margin-left: 15px;
            font-size: 1rem;
            transition: color 0.3s ease-in-out;
        }
        .btn-login:hover,
        .btn-signup:hover,
        .btn-categories:hover,
        .btn-tags:hover,
        .btn-polls:hover {
            color: #f8f9fa;
        }
        
        .btn-categories {
            background-color: #000000;
            border-color: #000000;
            color: #ffffff;
        }
        .btn-tags {
            background-color: #000000;
            border-color: #000000;
            color: #ffffff;
        }
    </style>
</head>
<body>
    <header class="page-header">
        <div class="container-fluid">
            <h1 class="navbar-brand">
                <a href="/"> H E R A P H E R I Blog</a>
            </h1>
            
            <div class="d-flex align-items-center ms-auto">
                <a href="{% url 'category_list' %}" class="btn btn-categories">Categories</a>
                <a href="{% url 'tag_list' %}" class="btn btn-tags">Tags</a>
                <a href="{% url 'polls:index' %}" class="btn btn-info">Polls</a>
                
                
            </div>
            <div style="float: right;">
            {% if user.is_authenticated %}
                    <a href="{% url 'post_new' %}" class="btn btn-create-post">
                        <i class="fas fa-pencil-alt"></i> New Post


                    </a>
                    <a id='logout' href="{% url 'user_logout' %}" class="btn btn-logout">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>     
                    
                        
                        
                    <a href="{% url 'user_detail' user_id=user.id %}" class="btn btn-info">
                        <i class="fas fa-user"></i> User Detail
                    </a>
                {% else %}
                    <a href="{% url 'user_login' %}" class="btn btn-login">Login</a>
                    <a href="{% url 'signup' %}" class="btn btn-signup">Sign up</a>
                {% endif %}
            </div>
        </div>
    </header>
    <main class="container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/js/all.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{%block content%}
{% for category in categories %}
    <article class="category">
       
        <h2><a href="{% url 'category_post' slug=category.slug %}">{{ category.title }}</a></h2>
        
    </article>
{% endfor %}
{%endblock%}

blog/templates/blog/category_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="category">
        <aside class="actions">
            {% if user.is_authenticated %}
            <a class="btn btn-secondary" href="{% url 'post_list' %}">
                {% include './icons/pencil-fill.svg' %}
                    </a>
            
            {%endif%}
        </aside>
       
        {% if category.published_date %}
            <time class="date">
                {{ category.published_date }}
            </time>
        {% endif %}
        
        <h2>{{ category.title }}</h2>
        <p>{{ category.text|linebreaksbr }}</p>
    </article>
{% endblock %}

blog/templates/blog/edit_profile.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{{slug}}</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        {% if user.is_authenticated %}
            <div style="text-align: right;">
                <a href="{% url 'post_edit' slug=post.slug %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit Post</a>
            </div>
            {% endif %}
        <style>
            h1 {
                text-align: left;
                margin-top: 0;
            }
            p{
                word-break: break-all;"
            }

            .reply-form {
                display: none;
            }

            .comment-section {
                margin-top: 20px;
            }

            .comment {
                margin-bottom: 30px;
                padding: 15px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .reply {
                margin-bottom: 15px;
                padding: 10px;
                border: 1px solid #eee;
                border-radius: 3px;
            }

            .reply-toggle-btn {
                cursor: pointer;
                color: #007bff;
                text-decoration: underline;
            }
        </style>

        {% if post.author.profile.image %}
        <img src="{{ post.author.profile.image.url }}" alt="{{ post.author.username }}">
        {% endif %}



        <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}"height ="80px" width="130px"><h1>{{ post.title }}</h1>
        
        {% if post.feature_image %}
            <img src="{{ post.feature_image.url }}" alt="{{ post.title }}" height="300px" width="900px">
        {% endif %}
        
        <p style="word-break: break-all;">{{ post.text|linebreaksbr }}</p>
        <p>Category: <a href="{% url 'category_post' slug=post.category.slug %}">{{ post.category.title }}</a></p>
         
        <p>Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'tag_post' slug=tag.slug %}">{{ tag.title }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        
        <li class="list-group-item"><strong>Avatar:</strong>  {% if user.avatar %}
            <img src="{{ user.avatar.url }}" alt="{{ user.Username }}" style="border-radius: 50%; height: 60px; width: 60px;" accept = "Jpg,png">
            {% endif %}<br> <strong>AUTHOR:</strong> {{ user.username }}</li>
        <li class="list-group-item"></li>

        
        <section class="comment-section">
            <h3>Add a Comment</h3>
            <form method="post" action="">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit">Submit Comment</button>
            </form>
        </section>

        <section class="existing-comments">
            <h3>Existing Comments</h3>
            {% for comment in comments %}
                <div class="comment">
                    <p>{{ comment.text }}</p>
                    <a class="reply-toggle-btn" data-target="{{ comment.id }}">Reply</a>
                    <br>
                    

                    <div class="reply-form" id="reply-form-{{ comment.id }}">
                        <form method="post">
                            {% csrf_token %}
                            {{ reply_form.as_p }}
                            <input type="hidden" name="parent_comment_id" value="{{ comment.id }}">
                            <button type="submit">Submit Reply</button>
                        </form>
                    </div>

                    {% for reply in comment.comment_set.all %}
                        <div class="reply">
                            <p>{{ reply.text }}</p>
                            <small><p>USERNAME :</p>{{ reply.author.username }} </small>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </section>

        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const replyToggleBtns = document.querySelectorAll('.reply-toggle-btn');

                replyToggleBtns.forEach(btn => {
                    btn.addEventListener('click', function() {
                        const commentId = this.getAttribute('data-target');
                        const replyForm = document.getElementById(`reply-form-${commentId}`);
                        replyForm.style.display = replyForm.style.display === 'none' ? 'block' : 'none';
                    });
                });
            });
        </script>
    </article>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New Post</h2>
    <form method="POST" enctype="multipart/form-data" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="post-list">
    {% for post in posts %}
    <article class="post">
        <h2 class="post-title">
            {% if post.thumbnail %}
            <a href="{% url 'post_detail' slug=post.slug %}"> <pre >   {{ post.title }}</pre> <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}"height ="150px" width="200px"> </a>
            {% endif %}
                </h2>
                
                <time class="date">
                    <style>
                        .post-container {
                            max-width: 100%;
                            overflow: hidden;
                        }



                        .post-text {
                            max-width: 100%;   
                            overflow: hidden; 
                            text-overflow: ellipsis;  
                            white-space: nowrap;  
                            word-wrap: break-word;
                        }
                    </style>
                    
                </time>
                <div class="post-container">
                    <p class="post-text">{{ post.text|linebreaksbr }}</p>
                </div>


                

                <p>Category: {{ post.category.title }}</p>
                <p>Tags: {% for tag in post.tags.all %}{{ tag.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

                    
            </article>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>

    
    
    
    <style>
        
        body {
            padding: 20px;
        }

        form {
            max-width: 400px;
            margin: auto;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: #28a745;
            color: #fff;
            padding: 10px 15px;
            border: none;
            cursor: pointer;
        }

        a {
            color: #007bff;
        }

        .list-group-item strong {
            display: inline-block;
            width: 150px; /* Adjust the width as needed */
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h2>Sign Up</h2>

    <form method="post" action="{% url 'signup' %}" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_username" class="form-label">Username:</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="id_email" class="form-label">Email:</label>
            {{ form.email }}
        </div>

        <!-- <li class="list-group-item"><strong>CITY:</strong> {{ user.city }}</li> -->
        <!-- <li class="list-group-item"><strong>COUNTRY:</strong> {{ user.country }}</li> -->



        <div class="mb-3">
            <label for="id_dob" class="form-label">Dob:</label>
            {{ form.dob }}
        </div>

        <div class="mb-3">
            <label for="id_country" class="form-label">Country:</label>
            {{ form.country }}
        </div>

        <div class="mb-3">
            <label for="id_city" class="form-label">City:</label>
            {{ form.city }}
        </div>



        <div class="mb-3">
            <label for="id_mobile_number" class="form-label">Mobile Number:</label>
            {{ form.mobile_number }}
        </div>
        <!-- <li class="list-group-item"><strong>DOB:</strong> {{ user.dob }}</li> -->

        <div class="mb-3">
            <label for="id_password1" class="form-label">Password:</label>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label for="id_password2" class="form-label">Confirm Password:</label>
            {{ form.password2 }}
        </div>
        <p>
            <input type="file" name="avatar" accept="image/*" id="avatar">
        </p>            
        
        <button type="submit" class="btn btn-success">Sign Up</button>
    </form>

    <p class="mt-3">Already have an account? <a href="{% url 'user_login' %}" class="text-primary">Login</a></p>

    <!-- Add Bootstrap JS and Popper.js if needed -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-e2e06f6d9f3a4143bb86c26d68e1abbdad75a6c3e9aef6b12d5f6d664bfa6716" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/tag_list.html
{% extends 'blog/base.html' %}

{%block content%}
 {% for tag in tags %}
    <article class="posts">
        <time class="date">
            {{ tag.published_date }}
        </time>
        <h2><a href="{% url 'tag_post' slug=tag.slug %}">{{ tag.title }}</a></h2>
        <p>{{ tag.text|linebreaksbr }}</p>
    </article>
{% endfor %} 
{%endblock%}

blog/templates/blog/tag_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="tag">
        <aside class="actions">
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="{% url 'post_list' %}">
                    {% include './icons/pencil-fill.svg' %}
                </a>
            {% endif %}
        </aside>

        {% if tag.created_date %}
            <time class="date">
                {{ tag.created_date }}
            </time>
        {% endif %}

        <h2>{{ tag.title }}</h2>
        <p>{{ tag.text|linebreaksbr }}</p>
    </article>
{% endblock %}

blog/templates/blog/user_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container mt-5">
    <center>
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">User Detail</h2>
                <ul class="list-group list-group-flush">


                    <center>
                        {% if user.avatar %}
                            <img src="{{ request.user.avatar.url }}" alt="{{ user.Username }}" style="border-radius: 50%; height: 60px; width: 60px;" accept = "Jpg,png">
                        
                            {% endif %}
                         
                    </center>
                    
                    

                    <li class="list-group-item"><strong>Username:</strong> {{ user.username }}</li>
                    <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
                    
                    <li class="list-group-item"><strong>Mobile No:</strong> {{ user.mobile_number }}</li>
                    <li class="list-group-item"><strong>CITY:</strong> {{ user.city }}</li>
                    <li class="list-group-item"><strong>COUNTRTY:</strong> {{ user.country }}</li>
                    <li class="list-group-item"><strong>DOB:</strong> {{ user.dob }}</li>



                        
                </ul>
                <a href="{% url 'edit_profile' user_id=user.id %}" class="btn btn-primary mt-3">Edit Profile</a>
            </div>
        </div>
    </center>
    </div>
{% endblock %}